(select DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
from ONLINE_SALE AS ONS
where SALES_DATE like '2022-03%'
UNION
select DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as SALES_DATE, PRODUCT_ID, NULL as USER_ID, SALES_AMOUNT
from OFFLINE_SALE AS OFS
where SALES_DATE like '2022-03%')
order by SALES_DATE, PRODUCT_ID, USER_ID